server:
  port: 8084
oauth2:
  client:
    clientId: beo-app-client
    clientSecret: e6aec4e0-e421-415a-8f84-d06237963831
    checkTokenEndpointUrl: http://192.168.0.76:8090/oauth/check_token
logging:
  level:
    root: INFO